FROM golang:1.18.5-alpine3.16

WORKDIR /server

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN  GOOS=linux GOARCH=amd64 go build -o ./bin/server ./server/main.go

EXPOSE 8080

CMD ["./bin/server"]