version: "3.7"
services:
  postgres:
    container_name: postgresdb
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    platform: linux/amd64
    container_name: server
    image: golang:1.19.0-alpine3.16
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: dockerfile.server
    restart: on-failure
    networks:
      - default
    depends_on:
      - postgres